(function(){
'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
var rnd=function(a,b){return Math.floor(Math.random()*(b-a+1))+a},pick=function(a){return a[rnd(0,a.length-1)]},fmt=function(n){return Math.abs(n-Math.round(n))<1e-9?String(Math.round(n)):Number(n.toFixed(3)).toLocaleString('de-DE')};
var N={numbers:'Zahlen & Rechnen',measure:'Größen & Messen',geometry:'Raum & Form',algebra:'Gleichungen & Funktionen',data:'Daten & Zufall',bbr:'BBR-Stil'};
var M={numbers:['½','Rechnen · Brüche · Prozent'],measure:['↔','Einheiten · Fläche · Volumen'],geometry:['△','Winkel · Figuren · Koordinaten'],algebra:['x','Terme · Gleichungen · Zuordnungen'],data:['▥','Diagramme · Kennwerte · Zufall'],bbr:['★','Sachaufgaben · Prüfungsstil']};
var L={lernen:'Lernen · RLP D',g:'Grundkurs · D–E',e:'Erweiterung · E'};
var pref=read('m8pref',{level:'g',advanced:false}),prog=read('m8prog',{}),S={screen:'home',level:pref.level||'g',advanced:!!pref.advanced,topic:'mix',qs:[],i:0,right:0,wrong:0,streak:0,answered:false,selected:null};
Object.keys(N).forEach(function(k){if(!prog[k])prog[k]={r:0,w:0}});
function read(k,d){try{var v=JSON.parse(localStorage.getItem(k));return v===null?d:v}catch(e){return d}}function save(){try{localStorage.setItem('m8pref',JSON.stringify({level:S.level,advanced:S.advanced}));localStorage.setItem('m8prog',JSON.stringify(prog))}catch(e){}}
function pc(k){var p=prog[k],n=p.r+p.w;return n?Math.round(100*p.r/n):0}function q(o){o.type=o.type||'num';o.unit=o.unit||'';return o}function mc(o){o.type='mc';o.options=o.options.sort(function(){return Math.random()-.5});return o}
function parse(v){var s=String(v||'').trim().replace(/\s/g,'').replace(',','.').replace(/%$/,'');if(/^[-+]?\d+\/[-+]?\d+$/.test(s)){var p=s.split('/').map(Number);return p[1]?p[0]/p[1]:NaN}return Number(s)}function ok(u,a){if(typeof a==='string')return String(u)===a;var x=parse(u);return Number.isFinite(x)&&Math.abs(x-a)<1e-6*Math.max(1,Math.abs(a))}
function bars(v){var m=Math.max.apply(null,v),s='<svg viewBox="0 0 340 130"><line x1="20" y1="110" x2="325" y2="110" stroke="#7890ad"/>';v.forEach(function(x,i){var h=75*x/m,p=34+i*58;s+='<rect x="'+p+'" y="'+(110-h)+'" width="34" height="'+h+'" rx="4" fill="#5aa7ff"/><text x="'+(p+17)+'" y="'+(105-h)+'" fill="#fff" font-size="10" text-anchor="middle">'+x+'</text>'});return s+'</svg>'}
function gen(k){var e=S.level!=='lernen';if(k==='numbers'){if(e&&rnd(0,2)===0){var p=pick([10,20,25,50]),g=rnd(40,300);return q({p:'Wie viel sind '+p+' % von '+g+'?',a:g*p/100,h:'Grundwert · Prozentsatz.',x:g+' · '+p+'/100 = '+fmt(g*p/100)+'.'})}var a=rnd(120,900),b=rnd(20,99);return q({p:'Berechne '+a+' − '+b+'.',a:a-b,h:'Subtrahiere stellenweise.',x:a+' − '+b+' = '+(a-b)+'.'})}
if(k==='measure'){if(e&&rnd(0,1)){var g=rnd(4,16),h=rnd(3,12);return q({p:'Dreieck: g = '+g+' cm, h = '+h+' cm. Fläche?',a:g*h/2,unit:'cm²',h:'A = g · h : 2.',x:'A = '+fmt(g*h/2)+' cm².'})}var m=rnd(2,15),cm=rnd(1,99);return q({p:'Wandle '+m+' m '+cm+' cm in Zentimeter um.',a:m*100+cm,unit:'cm',h:'1 m = 100 cm.',x:(m*100+cm)+' cm.'})}
if(k==='geometry'){if(e&&rnd(0,1)){var xx=rnd(-6,-1),yy=rnd(1,6);return mc({p:'In welchem Quadranten liegt P('+xx+' | '+yy+')?',options:['I','II','III','IV'],a:'II',h:'x negativ, y positiv.',x:'Der Punkt liegt im II. Quadranten.'})}var w1=rnd(35,70),w2=rnd(35,70);return q({p:'Dreieckswinkel: '+w1+'° und '+w2+'°. Dritter Winkel?',a:180-w1-w2,unit:'°',h:'Innenwinkelsumme = 180°.',x:(180-w1-w2)+'°.'})}
if(k==='algebra'){if(e&&rnd(0,1)){var x=rnd(-4,9),a=rnd(2,7),b=rnd(-7,7),c=a*x+b;return q({p:'Löse: '+a+'x '+(b>=0?'+ ':'− ')+Math.abs(b)+' = '+c+'.',a:x,h:'Zuerst +/− rückgängig, dann teilen.',x:'x = '+x+'.'})}var n=rnd(3,18),x=rnd(2,12);return q({p:'Löse: x + '+n+' = '+(x+n)+'.',a:x,h:'Ziehe '+n+' ab.',x:'x = '+x+'.'})}
if(k==='data'){if(e&&rnd(0,1)){var d=[4,6,8,10,12],z=pick([0,1,2]),v=d.map(function(x){return x+z}),sum=v.reduce(function(a,b){return a+b},0);return q({p:'Arithmetisches Mittel von '+v.join(', ')+'?',a:sum/5,h:'Summe durch Anzahl.',x:sum+' : 5 = '+fmt(sum/5)+'.'})}var v=[rnd(2,12),rnd(2,12),rnd(2,12),rnd(2,12),rnd(2,12)];return q({p:'Lies das Säulendiagramm: Wie groß ist der höchste Wert?',v:bars(v),a:Math.max.apply(null,v),h:'Suche die höchste Säule.',x:'Maximum: '+Math.max.apply(null,v)+'.'})}
if(k==='bbr'){if(e&&rnd(0,1)){var old=pick([40,60,80,120]),p=pick([10,20,25]);return q({p:'BBR-Stil: '+old+' € mit '+p+' % Rabatt. Neuer Preis?',a:old*(1-p/100),unit:'€',h:'Rabatt berechnen und abziehen.',x:fmt(old*(1-p/100))+' €.'})}var n=rnd(3,7),pr=pick([2.5,3,3.5,4]);return q({p:'BBR-Stil: '+n+' Tickets zu je '+fmt(pr)+' €. Gesamtpreis?',a:n*pr,unit:'€',h:'Anzahl · Einzelpreis.',x:fmt(n*pr)+' €.'})}}
function make(t){var ks=t==='mix'?Object.keys(N):[t],a=[];for(var i=0;i<12;i++){var k=pick(ks),o=gen(k);o.topic=k;if(S.advanced&&rnd(0,5)===0&&k==='measure'){var r=rnd(2,8);o=q({topic:k,p:'Zusatz: Kreisradius '+r+' cm. Umfang mit π≈3,14?',a:2*3.14*r,unit:'cm',h:'U = 2·π·r.',x:'U ≈ '+fmt(2*3.14*r)+' cm.'})}a.push(o)}return a}
function sync(){$$('#drawerLevels [data-level]').forEach(function(b){b.classList.toggle('active',b.dataset.level===S.level)});$('#advancedToggle').checked=S.advanced}
function render(){sync();if(S.screen==='home')home();else if(S.screen==='trainer')trainer();else result()}
function home(){var cards=Object.keys(N).map(function(k){return '<button class="topic-card" data-topic="'+k+'"><span class="topic-icon">'+M[k][0]+'</span><div><b>'+N[k]+'</b><small>'+M[k][1]+'</small><div class="mini-progress"><i style="width:'+pc(k)+'%"></i></div></div></button>'}).join('');$('#mainView').innerHTML='<section class="home-screen"><div class="hero"><div class="kicker">Grundwissen bis Ende Klasse 7</div><h1>Fit für Klasse 8</h1><p>Randomisierte Aufgaben aus allen fünf Leitideen des Berliner RLP – mit drei Niveaus, Tipps und Lernstand.</p></div><div class="level-picker"><button data-l="lernen" class="'+(S.level==='lernen'?'active':'')+'"><b>Lernen</b><small>RLP D</small></button><button data-l="g" class="'+(S.level==='g'?'active':'')+'"><b>Grundkurs</b><small>D–E</small></button><button data-l="e" class="'+(S.level==='e'?'active':'')+'"><b>Erweiterung</b><small>RLP E</small></button></div><div class="topic-grid">'+cards+'</div><div class="start-row"><button id="startMix" class="btn">▶ Gemischtes Training</button><button id="openInfo" class="btn secondary">RLP</button></div></section>';$$('[data-l]').forEach(function(b){b.onclick=function(){S.level=b.dataset.l;save();home();sync()}});$$('[data-topic]').forEach(function(b){b.onclick=function(){start(b.dataset.topic)}});$('#startMix').onclick=function(){start('mix')};$('#openInfo').onclick=function(){$('#infoDialog').showModal()}}
function start(t){S.topic=t;S.qs=make(t);S.i=S.right=S.wrong=S.streak=0;S.answered=false;S.selected=null;S.screen='trainer';render()}
function trainer(){var o=S.qs[S.i],ans=o.type==='mc'?'<div class="mc-grid">'+o.options.map(function(x){return '<button class="answer-btn" data-a="'+x+'">'+x+'</button>'}).join('')+'</div>':'<div class="numeric-row"><input id="answerInput" class="answer-input" inputmode="decimal" autocomplete="off" placeholder="Antwort">'+(o.unit?'<span class="unit-label">'+o.unit+'</span>':'')+'</div>';$('#mainView').innerHTML='<section class="trainer-screen"><div class="session-head"><div class="session-meta"><div class="line1"><b>'+(S.topic==='mix'?'Gemischtes Training':N[S.topic])+'</b><span class="pill">'+L[S.level]+'</span></div><small>Aufgabe '+(S.i+1)+' von 12 · '+N[o.topic]+'</small></div><div class="score-pill">✓ '+S.right+' · Serie '+S.streak+'</div><div class="progress-track"><i style="width:'+(S.i/12*100)+'%"></i></div></div><article class="question-card"><div class="q-top"><span class="q-label">'+N[o.topic]+'</span><span class="q-difficulty">'+(S.level==='lernen'?'D':S.level==='g'?'D–E':'E')+'</span></div><div class="q-body"><h2>'+o.p+'</h2>'+(o.v?'<div class="visual">'+o.v+'</div>':'')+'<div class="answer-area">'+ans+'</div></div><div id="feedback" class="q-feedback">💡 <span>Bei Bedarf kannst du einen Tipp einblenden.</span></div></article><div class="session-actions"><button id="quitBtn" class="btn ghost">⌂</button><button id="checkBtn" class="btn main-action">Prüfen</button><button id="hintBtn" class="btn secondary">Tipp</button></div></section>';if(o.type==='mc')$$('.answer-btn').forEach(function(b){b.onclick=function(){if(S.answered)return;S.selected=b.dataset.a;$$('.answer-btn').forEach(function(x){x.classList.toggle('selected',x===b)})}});else{var i=$('#answerInput');i.onkeydown=function(e){if(e.key==='Enter')check()}}$('#checkBtn').onclick=check;$('#hintBtn').onclick=function(){$('#feedback').innerHTML='💡 <span><strong>Tipp:</strong> '+o.h+'</span>'};$('#quitBtn').onclick=function(){S.screen='home';render()}}
function check(){var o=S.qs[S.i];if(S.answered){if(S.i===11){S.screen='result';render()}else{S.i++;S.answered=false;S.selected=null;render()}return}var u=o.type==='mc'?S.selected:$('#answerInput').value;if(u===null||String(u).trim()===''){toast('Bitte zuerst antworten.');return}var yes=o.type==='mc'?String(u)===String(o.a):ok(u,o.a);S.answered=true;if(yes){S.right++;S.streak++;prog[o.topic].r++}else{S.wrong++;S.streak=0;prog[o.topic].w++}save();var f=$('#feedback');f.className='q-feedback '+(yes?'good':'bad');f.innerHTML=(yes?'✓':'✕')+' <span><strong>'+(yes?'Richtig!':'Noch nicht.')+'</strong> '+o.x+'</span>';if(o.type==='mc')$$('.answer-btn').forEach(function(b){if(b.dataset.a===String(o.a))b.classList.add('correct');else if(b.dataset.a===String(u)&&!yes)b.classList.add('wrong');b.disabled=true});else $('#answerInput').disabled=true;$('#checkBtn').textContent=S.i===11?'Auswertung':'Nächste Aufgabe';$('#hintBtn').disabled=true}
function result(){var p=Math.round(S.right/12*100);$('#mainView').innerHTML='<section class="result-screen"><div class="result-card"><div class="result-ring" style="--pct:'+p+'%"><div><b>'+p+'%</b></div></div><div class="kicker">Training abgeschlossen</div><h2>'+(S.topic==='mix'?'Gemischtes Grundwissen':N[S.topic])+'</h2><p>'+(p>=80?'Sehr gute Basis.':'Weiter üben lohnt sich.')+'</p><div class="result-stats"><div><b>'+S.right+'</b><small>richtig</small></div><div><b>'+S.wrong+'</b><small>offen</small></div><div><b>'+S.streak+'</b><small>Serie</small></div></div><div class="result-actions"><button id="againBtn" class="btn">Noch eine Runde</button><button id="homeBtn" class="btn secondary">Startseite</button></div></div></section>';$('#againBtn').onclick=function(){start(S.topic)};$('#homeBtn').onclick=function(){S.screen='home';render()}}
function openD(){$('#drawerBackdrop').hidden=false;$('#drawer').classList.add('open')}function closeD(){$('#drawer').classList.remove('open');setTimeout(function(){$('#drawerBackdrop').hidden=true},220)}
$('#menuBtn').onclick=openD;$('#closeDrawer').onclick=closeD;$('#drawerBackdrop').onclick=closeD;$('#drawerLevels').onclick=function(e){var b=e.target.closest('[data-level]');if(b){S.level=b.dataset.level;save();sync();closeD();if(S.screen==='home')home()}};$('#menuHome').onclick=function(){S.screen='home';closeD();render()};$('#menuCalc').onclick=function(){closeD();setTimeout(function(){$('#calcDialog').showModal()},150)};$('#calcShortcut').onclick=function(){$('#calcDialog').showModal()};$('#menuRlp').onclick=function(){closeD();setTimeout(function(){$('#infoDialog').showModal()},150)};$('#advancedToggle').onchange=function(e){S.advanced=e.target.checked;save();toast(S.advanced?'Zusatzthemen an':'Zusatzthemen aus')};$('#menuReset').onclick=function(){Object.keys(N).forEach(function(k){prog[k]={r:0,w:0}});save();closeD();S.screen='home';render();toast('Lernstand zurückgesetzt')};$('#menuQr').onclick=function(){closeD();setTimeout(function(){var url=location.href.split('#')[0],box=$('#qrCode');box.innerHTML='';$('#qrUrl').textContent=url;var im=document.createElement('img');im.width=240;im.height=240;im.alt='QR-Code';im.src='https://api.qrserver.com/v1/create-qr-code/?size=300x300&margin=8&data='+encodeURIComponent(url);box.appendChild(im);$('#qrDialog').showModal()},150)};
var ce='';$('#calcGrid').onclick=function(e){var b=e.target.closest('[data-calc]');if(!b)return;var v=b.dataset.calc;if(v==='clear'){ce='';$('#calcResult').textContent='0'}else if(v==='back')ce=ce.slice(0,-1);else if(v==='sqrt')ce+='sqrt(';else if(v==='square')ce+='**2';else if(v==='pi')ce+='PI';else if(v==='equals'){try{var x=ce.replace(/,/g,'.').replace(/PI/g,'('+Math.PI+')').replace(/sqrt\(/g,'Math.sqrt(').replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');if(!/^[0-9+\-*/().\sMathsqrtPI]+$/.test(x))throw 0;var n=Function('"use strict";return('+x+')')();$('#calcResult').textContent=fmt(n)}catch(err){$('#calcResult').textContent='Fehler'}return}else ce+=v;$('#calcExpression').textContent=ce||' '};
var tt;function toast(t){var x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(tt);tt=setTimeout(function(){x.classList.remove('show')},1600)}
try{render()}catch(err){$('#mainView').innerHTML='<section class="home-screen"><div class="hero"><div class="kicker">Startfehler</div><h1>Trainer konnte nicht geladen werden</h1><p>'+String(err.message||err)+'</p></div></section>';console.error(err)}
})();